"""new fields for posts AI support

Revision ID: 1591b33a0c48
Revises: 4f8a64992c91
Create Date: 2026-04-22 00:22:20.072289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1591b33a0c48"
down_revision: Union[str, Sequence[str], None] = "4f8a64992c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("ai_plant_id", sa.Integer(), nullable=True))
    op.add_column("posts", sa.Column("ai_confidence", sa.Float(), nullable=True))
    op.add_column("posts", sa.Column("user_plant_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "user_plant_id")
    op.drop_column("posts", "ai_confidence")
    op.drop_column("posts", "ai_plant_id")
    # ### end Alembic commands ###
