"""add_content_tables

Revision ID: 2d27f3995b5a
Revises: 6b8d8a744a8b
Create Date: 2026-04-01 17:26:51.656353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d27f3995b5a'
down_revision: Union[str, Sequence[str], None] = '6b8d8a744a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocations',
    sa.Column('geo_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('geo_id')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('post_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('post_geolocations',
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('geo_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['geo_id'], ['geolocations.geo_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], )
    )
    op.create_table('post_users',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.create_table('user_geolocations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('geo_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['geo_id'], ['geolocations.geo_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.alter_column('user_accounts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_accounts', 'platform_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_accounts', 'platform_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'consent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'consent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_accounts', 'platform_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_accounts', 'platform_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_accounts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('user_geolocations')
    op.drop_table('post_users')
    op.drop_table('post_geolocations')
    op.drop_table('posts')
    op.drop_table('geolocations')
    # ### end Alembic commands ###
