"""add_settings_tables

Revision ID: 4f8a64992c91
Revises: 2d27f3995b5a
Create Date: 2026-04-01 18:09:52.494079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8a64992c91'
down_revision: Union[str, Sequence[str], None] = '2d27f3995b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_sections',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('bot_commands',
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('command_description', sa.Text(), nullable=True),
    sa.Column('time_create', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id_create', sa.UUID(), nullable=True),
    sa.Column('user_update', sa.UUID(), nullable=True),
    sa.Column('platform_enabled', sa.String(), nullable=False),
    sa.Column('time_update', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id_create'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_update'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('command_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_commands')
    op.drop_table('faq_sections')
    # ### end Alembic commands ###
